Expand NPC config table and sprite group table
pk-hack/CoilSnake pull request #281
Opened 2023-12-10 22:54 UTC by tolmar

As discussed in the discord. This lets NPC configs and sprite groups expand.

Please test and carefully review, I could easily have missed something up on integration.

Adding new NPCs/sprites crashes EbProjEditor. I'll be making another patch for that repo.

2023-12-10 23:33 UTC, charasyn requested changes
I think we should move these Pointer classes to a different file and rename them.. Other than that the change looks good!

Just checking, this version shouldn't affect EbProjEdit compatibility unless the YML files actually have extra entries in them, right?

2023-12-10 23:33 UTC, charasyn commented on coilsnake/modules/eb/SpriteGroupModule.py
> +    ]
Can you change these to `AsmPointerReference` instances instead? I think that would be nicer than needing to know they're all AsmPointers

Additionally, can you rename the attribute to `SPRITE_GROUP_TABLE_REFERENCES` to match with the new naming convention?

2023-12-10 23:33 UTC, charasyn commented on coilsnake/modules/eb/ExpandedTablesModule.py
> +
nit: remove newly added newline

2023-12-10 23:33 UTC, charasyn commented on coilsnake/modules/eb/ExpandedTablesModule.py
>  class AsmPointer(object):
Can you:
1. Rename `AsmPointer` to `AsmPointerReference` (and similar with `XlPointer`)
2. Rename `write` to `relocate`
3. Move both classes to `coilsnake/util/eb/pointer.py`
4. Remove the subclassing of `object` (this is a Python2 leftover, and isn't necessary anymore)

Thanks!
P.S. If you have time and want to, go ahead and add a base class `PointerReference` with a `relocate` method which just raises `NotImplementedError` :)

2023-12-11 05:13 UTC, tolmar commented
> Just checking, this version shouldn't affect EbProjEdit compatibility unless the YML files actually have extra entries in them, right?

Yeah, EbProjEdit is fine until you actually use the new expansions.

2023-12-11 19:50 UTC, charasyn approved these changes
Looks good to me

2023-12-11 19:50 UTC, merged